<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXkksfkr\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXkksfkr/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXkksfkr.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXkksfkr\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXkksfkr\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Xkksfkr',
    'container.build_id' => 'cae6557c',
    'container.build_time' => 1555077623,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXkksfkr');
